name: Release

on:
  release:
    types: [created]

jobs:
  build-linux:
    name: Build Linux Binaries
    runs-on: ubuntu-latest

    steps:
      - name: musl-tools
        run: |
          sudo apt-get install musl-tools
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-musl/release/bobstop
          asset_name: bobstop
          tag: ${{ github.ref }}

  build-windows:
    name: Build Windows Binaries
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --release
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/bobstop.exe
          asset_name: bobstop.exe
          tag: ${{ github.ref }}